name = "serverless-api"
type = "javascript"
account_id = "bb14042d332ac1d9305f243729120c92"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-10-14"
kv_namespaces = [{ binding = "SOCIAL_MEDIA", preview_id = "390a9231108441918ffb73bda82efdb5", id="390a9231108441918ffb73bda82efdb5"}]